In [27]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sqlalchemy import create_engine
import dataframe_image as dfi

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler

In [24]:
# 1.连接数据库
engine = create_engine(
    "mysql+pymysql://root:88888888@localhost:3306/user_behavior_db")

In [4]:
df_guild = pd.read_sql("select * from guild_info", engine)
df_guild

,guild_id,guild_name,region,established_date,training_frequency,guild_efficiency_score,anchor_count,avg_anchor_revenue_usd,avg_audience_retention
0,1,Guild_001,southeast_asia,2024-08-10,MEDIUM,0.5036,18,5176.71,0.4486
1,2,Guild_002,Others,2023-06-14,HIGH,0.6979,6,10307.10,0.5544
2,3,Guild_003,North_America,2024-01-25,HIGH,0.9215,33,14437.80,0.5193
3,4,Guild_004,Middle_East,2023-09-12,LOW,0.3307,8,1828.44,0.2987
4,5,Guild_005,Southeast_Asia,2022-12-06,MEDIUM,0.3380,21,7454.34,0.4379
...,...,...,...,...,...,...,...,...,...
86,96,Guild_096,Middle_East,2024-01-01,MEDIUM,0.5633,29,5557.70,0.3834
87,97,Guild_097,Middle_East,2023-04-12,LOW,0.3299,32,1833.43,0.4052
88,98,Guild_098,Southeast_Asia,2022-12-14,HIGH,0.8003,26,7603.15,0.5333
89,99,Guild_099,Southeast_Asia,2022-12-21,MEDIUM,0.4990,26,6266.31,0.3259
90,100,Guild_100,Southeast_Asia,2023-03-06,HIGH,0.6782,25,6901.92,0.5213

In [12]:
training_table = df_guild.groupby('training_frequency').agg(
    公会个数 = ('guild_id', 'count'),
    公会效率得分avg = ('guild_efficiency_score', 'mean'),
    主播人数 = ('anchor_count', 'mean'),
    主播平均收入 = ('avg_anchor_revenue_usd', 'mean'),
    平均观众留存率 = ('avg_audience_retention', 'mean'),
).reset_index()

training_table['平均观众留存率'] = (training_table['平均观众留存率'] * 100).round(2)
training_table

  training_frequency  公会个数  公会效率得分avg       主播人数        主播平均收入  平均观众留存率
0               HIGH    26   0.756096  19.384615  11574.504231    57.28
1                LOW    29   0.293907  21.241379   1979.993793    30.45
2             MEDIUM    36   0.500914  21.333333   5276.539167    43.07

In [15]:
training_table['training_frequency'] = pd.Categorical(
    training_table['training_frequency'],['LOW','MEDIUM','HIGH'],ordered=True)
training_table_sorted = training_table.sort_values('training_frequency').reset_index(drop=True)[['training_frequency','公会效率得分avg','主播平均收入','平均观众留存率']]
training_table_sorted

  training_frequency  公会效率得分avg        主播平均收入  平均观众留存率
0                LOW   0.293907   1979.993793    30.45
1             MEDIUM   0.500914   5276.539167    43.07
2               HIGH   0.756096  11574.504231    57.28

In [16]:
dfi.export(
    training_table_sorted,'按训练频次公会运营情况.png',table_conversion='chrome',dpi=300)

In [18]:
df_guild['region'] = df_guild['region'].str.title()

region_table = df_guild.groupby('region').agg(
    公会个数 = ('guild_id', 'count'),
    公会效率得分avg = ('guild_efficiency_score', 'mean'),
    主播人数 = ('anchor_count', 'mean'),
    主播平均收入 = ('avg_anchor_revenue_usd', 'mean'),
    平均观众留存率 = ('avg_audience_retention', 'mean'),
).reset_index()

region_table['平均观众留存率'] = (region_table['平均观众留存率'] * 100).round(2)
region_table

             region  公会个数  公会效率得分avg       主播人数       主播平均收入  平均观众留存率
0  Chinese_Speaking     7   0.487671  22.285714  5670.370000    43.47
1       Middle_East    19   0.448632  19.000000  4492.027368    41.72
2     North_America    16   0.509375  21.750000  6178.148750    43.41
3            Others     4   0.756175  23.000000  8737.662500    52.24
4    Southeast_Asia    45   0.513384  20.688889  6432.671111    42.73

In [20]:
region_table_pic = region_table[['region', '公会个数','公会效率得分avg', '主播平均收入', '平均观众留存率']]
dfi.export(
    region_table_pic,'按地区公会运营情况.png',table_conversion='chrome',dpi=300)

In [21]:
# 1. 选择你需要分析的核心数值列
columns_to_analyze = [
    'guild_efficiency_score',
    'anchor_count',
    'avg_anchor_revenue_usd',
    'avg_audience_retention'
]

# 2. 计算皮尔逊相关系数矩阵
correlation_matrix = df_guild[columns_to_analyze].corr()

friendly_names = {
    'guild_efficiency_score': '公会效率得分',
    'anchor_count': '主播人数',
    'avg_anchor_revenue_usd': '平均主播营收(USD)',
    'avg_audience_retention': '平均观众留存率'
}
correlation_matrix.rename(columns=friendly_names, index=friendly_names, inplace=True)

print("--- 多维相关性分析矩阵 ---")
correlation_matrix.round(4)

--- 多维相关性分析矩阵 ---

             公会效率得分    主播人数  平均主播营收(USD)  平均观众留存率
公会效率得分       1.0000 -0.0511       0.8396   0.7666
主播人数        -0.0511  1.0000      -0.0852  -0.1634
平均主播营收(USD)  0.8396 -0.0852       1.0000   0.7937
平均观众留存率      0.7666 -0.1634       0.7937   1.0000

In [22]:
dfi.export(
    correlation_matrix,'公会运营效率分析情况.png',table_conversion='chrome',dpi=300)

In [26]:
df_anchor = pd.read_sql("select * from anchor_base_info", engine)
df_anchor

,anchor_id,user_id,guild_id,join_date,region,content_category,anchor_level,follower_count,audience_retention_rate,avg_daily_stream_hours,pk_win_rate,total_gift_received_usd,revenue_last_2w_change,churn_risk_label,is_new_anchor,first_week_stream_days
0,1,1,23,2025-03-07,Southeast_Asia,Game,B,17538,0.2286,3.47,0.8241,2435.58,0.0804,MEDIUM,1,6
1,2,2,48,2024-01-01,Middle_East,Music,C,107,0.2578,1.87,0.2544,70.76,-0.0140,MEDIUM,0,-1
2,3,3,8,2024-06-24,Southeast_Asia,Game,C,2979,0.1830,4.55,0.5957,204.45,-0.1912,MEDIUM,0,-1
3,4,4,89,2023-04-18,Southeast_Asia,Chat,C,12339,0.3087,5.12,0.1956,618.05,-0.3817,HIGH,0,-1
4,5,5,64,2023-10-17,Southeast_Asia,Dance,C,1111,0.1670,2.44,0.7937,803.40,0.1866,MEDIUM,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1966,1996,1996,40,2023-07-30,Southeast_Asia,Talent,C,720,0.3974,4.81,0.5431,376.99,-0.0023,LOW,0,-1
1967,1997,1997,62,2023-04-06,Southeast_Asia,Music,C,906,0.2040,4.04,0.6149,36.28,0.0006,MEDIUM,0,-1
1968,1998,1998,100,2022-11-29,Southeast_Asia,Music,A,137584,0.5859,1.89,0.7514,30321.19,-0.1000,LOW,0,-1
1969,1999,1999,2,2023-07-10,Others,Chat,C,1480,0.1841,3.13,0.6685,256.68,-0.0161,MEDIUM,0,-1
1970,2000,2000,57,2024-08-20,Southeast_Asia,Chat,B,3509,0.3064,1.10,0.7427,1181.95,-0.0501,LOW,0,-1

In [33]:
anchor_received_usd = df_anchor.groupby('anchor_level').agg(
    total_revenue_usd=('total_gift_received_usd', 'sum'),
    count = ('anchor_id', 'count'),
)
anchor_received_usd

              total_revenue_usd  count
anchor_level
A                    2162449.00    191
B                     942252.63    450
C                     445559.86   1324
S                     473017.43      6

In [38]:
df_top_anchors = df_anchor[(df_anchor['anchor_level'] == 'S') | (df_anchor['anchor_level'] == 'A')].copy()


# 准备特征矩阵 X 和目标标签 y
# 特征：提取两周流水变动、开播时长、观众留存率作为自变量
features = ['revenue_last_2w_change', 'avg_daily_stream_hours', 'audience_retention_rate', 'pk_win_rate']
X = df_top_anchors[features].copy()

# 目标：将现有的风险标签转为二分类数值（我们将 HIGH 视为 1，LOW/MEDIUM 视为 0）
y = df_top_anchors['churn_risk_label'].apply(lambda x: 1 if x == 'HIGH' else 0)


# 划分训练集与测试集（ 70% 训练，30% 测试）
# stratify=y 确保训练集和测试集中“高危流失”主播的比例完全一致，保障实验严谨性
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# 特征标准化
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 用训练集构建逻辑回归模型
model = LogisticRegression(class_weight='balanced', random_state=42)
model.fit(X_train_scaled, y_train)

# 用测试集检验模型的可信度
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

print("基于测试集的模型可信度检验报告")
print(classification_report(y_test, y_pred, target_names=['非高危', '高危流失(HIGH)']))

print("模型区分流失风险的能力 (ROC-AUC)")
print(f"ROC-AUC 得分: {round(roc_auc_score(y_test, y_prob), 4)} \n")

print("由算法拟合出的科学权重（标准化系数）")
for feat, coef in zip(features, model.coef_[0]):
    print(f"特征 [{feat}] 的标准化回归系数: {round(coef, 4)}")
print(f"截距项 (Intercept / Bias): {round(model.intercept_[0], 4)}")

基于测试集的模型可信度检验报告
              precision    recall  f1-score   support

         非高危       1.00      0.98      0.99        51
  高危流失(HIGH)       0.90      1.00      0.95         9

    accuracy                           0.98        60
   macro avg       0.95      0.99      0.97        60
weighted avg       0.98      0.98      0.98        60

模型区分流失风险的能力 (ROC-AUC)
ROC-AUC 得分: 1.0

由算法拟合出的科学权重（标准化系数）
特征 [revenue_last_2w_change] 的标准化回归系数: -3.2123
特征 [avg_daily_stream_hours] 的标准化回归系数: 0.1268
特征 [audience_retention_rate] 的标准化回归系数: -1.1973
特征 [pk_win_rate] 的标准化回归系数: -0.0765
截距项 (Intercept / Bias): -3.336